In [271]:
import pandas as pd

In [272]:
data = pd.read_csv("C:\\Users\\USER_PC_SA\\Desktop\\Linear Regression model\\Data\\Car_price.csv")
data.iloc[: ,10:]

,car_length,carwidth,carheight,curbweight,enginetype,cylinder_number,engine_size,fuelsystem,bore_ratio,stroke,compressionratio,horsepower,peakrpm,city_mpg,high_way_mpg,price
0,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,188.8,68.9,55.5,2952,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,188.8,68.8,55.5,3049,ohc,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,188.8,68.9,55.5,3012,ohcv,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,188.8,68.9,55.5,3217,ohc,six,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,188.8,68.9,55.5,3062,ohc,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [273]:
data.cylinder_number.value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: cylinder_number, dtype: int64

In [274]:
data.info

<bound method DataFrame.info of      car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std
1         2          3       alfa-romero stelvio      gas        std
2         3          1  alfa-romero Quadrifoglio      gas        std
3         4          2               audi 100 ls      gas        std
4         5          2                audi 100ls      gas        std
..      ...        ...                       ...      ...        ...
200     201         -1           volvo 145e (sw)      gas        std
201     202         -1               volvo 144ea      gas      turbo
202     203         -1               volvo 244dl      gas        std
203     204         -1                 volvo 246   diesel      turbo
204     205         -1               volvo 264gl      gas      turbo

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...
1          two  convertible        rwd          front       88.6  ...
2          two    hatchback        rwd          front       94.5  ...
3         four        sedan        fwd          front       99.8  ...
4         four        sedan        4wd          front       99.4  ...
..         ...          ...        ...            ...        ...  ...
200       four        sedan        rwd          front      109.1  ...
201       four        sedan        rwd          front      109.1  ...
202       four        sedan        rwd          front      109.1  ...
203       four        sedan        rwd          front      109.1  ...
204       four        sedan        rwd          front      109.1  ...

     engine_size  fuelsystem  bore_ratio  stroke compressionratio horsepower  \
0            130        mpfi        3.47    2.68              9.0        111
1            130        mpfi        3.47    2.68              9.0        111
2            152        mpfi        2.68    3.47              9.0        154
3            109        mpfi        3.19    3.40             10.0        102
4            136        mpfi        3.19    3.40              8.0        115
..           ...         ...         ...     ...              ...        ...
200          141        mpfi        3.78    3.15              9.5        114
201          141        mpfi        3.78    3.15              8.7        160
202          173        mpfi        3.58    2.87              8.8        134
203          145         idi        3.01    3.40             23.0        106
204          141        mpfi        3.78    3.15              9.5        114

     peakrpm city_mpg  high_way_mpg    price
0       5000       21            27  13495.0
1       5000       21            27  16500.0
2       5000       19            26  16500.0
3       5500       24            30  13950.0
4       5500       18            22  17450.0
..       ...      ...           ...      ...
200     5400       23            28  16845.0
201     5300       19            25  19045.0
202     5500       18            23  21485.0
203     4800       26            27  22470.0
204     5400       19            25  22625.0

[205 rows x 26 columns]>

In [275]:
data = data1.drop(["car_ID" , "symboling" ] , axis=1)
data.doornumber = data.doornumber.astype(pd.StringDtype())
data.doornumber.value_counts()

four    115
two      90
Name: doornumber, dtype: Int64

In [276]:
x = list(data.iloc[: ,9:].columns)
x.remove("enginetype")
x.remove("price")
x.remove("cylinder_number")
numeric_data =x
numeric_data

['carwidth',
 'carheight',
 'curbweight',
 'engine_size',
 'fuelsystem',
 'bore_ratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'city_mpg',
 'high_way_mpg']

In [277]:
import matplotlib.pyplot as plt
#for i in numeric_data:
#        plt.figure()
#        print(plt.bar(data[i], data["price"]))

In [278]:
df = pd.DataFrame(data.loc[ : , ['wheelbase',
 'car_length',
 'carwidth',
 'carheight',
 'curbweight',
 'engine_size',
 'bore_ratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'city_mpg',
 'high_way_mpg']])
df

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,peakrpm,city_mpg,high_way_mpg
0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28
201,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25
202,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23
203,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27
204,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25

In [279]:

from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler(feature_range=(0 , 2) , copy=True)
zi = ms.fit_transform(df)
zi = pd.DataFrame(zi , columns=['wheelbase',
 'car_length',
 'carwidth',
 'carheight',
 'curbweight',
 'engine_size',
 'bore_ratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'city_mpg',
 'high_way_mpg'])
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,peakrpm,city_mpg,high_way_mpg
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,0.693878,0.333333,0.526316
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,1.102041,0.611111,0.736842
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,1.102041,0.277778,0.315789
...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.555556,0.631579
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,0.938776,0.333333,0.473684
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,1.102041,0.277778,0.368421
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,0.530612,0.722222,0.578947
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.333333,0.473684

In [280]:
data.cylinder_number

0      four
1      four
2       six
3      four
4      five
       ...
200    four
201    four
202     six
203     six
204    four
Name: cylinder_number, Length: 205, dtype: object

In [281]:
new = data.cylinder_number.replace(["one" , "two" , "three" , "four" ,"six" ,"five" , "twelve" , "eight"] , value=[1,2,3,4,6,5,12,9] )
new

0      4
1      4
2      6
3      4
4      5
      ..
200    4
201    4
202    6
203    6
204    4
Name: cylinder_number, Length: 205, dtype: int64

In [282]:
zi["cylinder_number"] = new
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,peakrpm,city_mpg,high_way_mpg,cylinder_number
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947,4
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947,4
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,0.693878,0.333333,0.526316,6
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,1.102041,0.611111,0.736842,4
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,1.102041,0.277778,0.315789,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.555556,0.631579,4
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,0.938776,0.333333,0.473684,4
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,1.102041,0.277778,0.368421,6
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,0.530612,0.722222,0.578947,6
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.333333,0.473684,4

In [283]:
dim = pd.get_dummies(data.fueltype)
zi = pd.concat([zi , dim] , axis="columns" )
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,peakrpm,city_mpg,high_way_mpg,cylinder_number,diesel,gas
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947,4,0,1
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,0.693878,0.444444,0.578947,4,0,1
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,0.693878,0.333333,0.526316,6,0,1
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,1.102041,0.611111,0.736842,4,0,1
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,1.102041,0.277778,0.315789,5,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.555556,0.631579,4,0,1
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,0.938776,0.333333,0.473684,4,0,1
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,1.102041,0.277778,0.368421,6,0,1
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,0.530612,0.722222,0.578947,6,1,0
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,1.020408,0.333333,0.473684,4,0,1

In [284]:
dim1 = pd.get_dummies(data.carbody)
zi = pd.concat([zi , dim1] , axis="columns" )
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,city_mpg,high_way_mpg,cylinder_number,diesel,gas,convertible,hardtop,hatchback,sedan,wagon
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,0.444444,0.578947,4,0,1,1,0,0,0,0
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,0.444444,0.578947,4,0,1,1,0,0,0,0
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,0.333333,0.526316,6,0,1,0,0,1,0,0
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,0.611111,0.736842,4,0,1,0,0,0,1,0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,0.277778,0.315789,5,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,0.555556,0.631579,4,0,1,0,0,0,1,0
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,0.333333,0.473684,4,0,1,0,0,0,1,0
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,0.277778,0.368421,6,0,1,0,0,0,1,0
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,0.722222,0.578947,6,1,0,0,0,0,1,0
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,0.333333,0.473684,4,0,1,0,0,0,1,0

In [285]:
dim2 = pd.get_dummies(data.drivewheel)
zi = pd.concat([zi , dim2] , axis="columns" )
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,diesel,gas,convertible,hardtop,hatchback,sedan,wagon,4wd,fwd,rwd
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,0,1,1,0,0,0,0,0,0,1
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,0,1,1,0,0,0,0,0,0,1
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,0,1,0,0,1,0,0,0,0,1
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,0,1,0,0,0,1,0,0,1,0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,0,1,0,0,0,1,0,0,0,1
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,0,1,0,0,0,1,0,0,0,1
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,0,1,0,0,0,1,0,0,0,1
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,1,0,0,0,0,1,0,0,0,1
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,0,1,0,0,0,1,0,0,0,1

In [286]:
dim3 = pd.get_dummies(data.aspiration)
zi = pd.concat([zi , dim3] , axis="columns" )
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,convertible,hardtop,hatchback,sedan,wagon,4wd,fwd,rwd,std,turbo
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,0,0,0,0,0,0,1,1,0
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,0,0,0,0,0,0,1,1,0
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,0,0,1,0,0,0,0,1,1,0
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,0,0,0,1,0,0,1,0,1,0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,0,0,0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,0,0,0,1,0,0,0,1,1,0
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,0,0,0,1,0,0,0,1,0,1
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,0,0,0,1,0,0,0,1,1,0
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,0,0,0,1,0,0,0,1,0,1
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,0,0,0,1,0,0,0,1,0,1

In [287]:
dim3 = pd.get_dummies(data.enginetype)
zi = pd.concat([zi , dim3] , axis="columns" )
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,rwd,std,turbo,dohc,dohcv,l,ohc,ohcf,ohcv,rotor
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,1,0,1,0,0,0,0,0,0
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,1,0,1,0,0,0,0,0,0
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,1,1,0,0,0,0,0,0,1,0
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,0,1,0,0,0,0,1,0,0,0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,1,1,0,0,0,0,1,0,0,0
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,1,0,1,0,0,0,1,0,0,0
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,1,1,0,0,0,0,0,0,1,0
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,1,0,1,0,0,0,1,0,0,0
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,1,0,1,0,0,0,1,0,0,0

In [288]:
zi["price"] = data.price
zi

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,std,turbo,dohc,dohcv,l,ohc,ohcf,ohcv,rotor,price
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,0,1,0,0,0,0,0,0,13495.0
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,0,1,0,0,0,0,0,0,16500.0
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,1,0,0,0,0,0,0,1,0,16500.0
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,1,0,0,0,0,1,0,0,0,13950.0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,1,0,0,0,0,1,0,0,0,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,1,0,0,0,0,1,0,0,0,16845.0
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,0,1,0,0,0,1,0,0,0,19045.0
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,1,0,0,0,0,0,0,1,0,21485.0
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,0,1,0,0,0,1,0,0,0,22470.0
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,0,1,0,0,0,1,0,0,0,22625.0

In [289]:
from sklearn.model_selection import train_test_split

In [290]:
X = zi.drop("price" , axis=1)
Y = zi.price
Y=Y.astype(int)
X

,wheelbase,car_length,carwidth,carheight,curbweight,engine_size,bore_ratio,stroke,compressionratio,horsepower,...,rwd,std,turbo,dohc,dohcv,l,ohc,ohcf,ohcv,rotor
0,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,1,0,1,0,0,0,0,0,0
1,0.116618,0.826866,0.633333,0.166667,0.822343,0.520755,1.328571,0.580952,0.2500,0.525000,...,1,1,0,1,0,0,0,0,0,0
2,0.460641,0.898507,0.866667,0.766667,1.035687,0.686792,0.200000,1.333333,0.2500,0.883333,...,1,1,0,0,0,0,0,0,1,0
3,0.769679,1.059701,0.983333,1.083333,0.658650,0.362264,0.928571,1.266667,0.3750,0.450000,...,0,1,0,0,0,0,1,0,0,0
4,0.746356,1.059701,1.016667,1.083333,1.036462,0.566038,0.928571,1.266667,0.1250,0.558333,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1.311953,1.423881,1.433333,1.283333,1.135764,0.603774,1.771429,1.028571,0.3125,0.550000,...,1,1,0,0,0,0,1,0,0,0
201,1.311953,1.423881,1.416667,1.283333,1.211016,0.603774,1.771429,1.028571,0.2125,0.933333,...,1,0,1,0,0,0,1,0,0,0
202,1.311953,1.423881,1.433333,1.283333,1.182312,0.845283,1.485714,0.761905,0.2250,0.716667,...,1,1,0,0,0,0,0,0,1,0
203,1.311953,1.423881,1.433333,1.283333,1.341350,0.633962,0.671429,1.266667,2.0000,0.483333,...,1,0,1,0,0,0,1,0,0,0
204,1.311953,1.423881,1.433333,1.283333,1.221102,0.603774,1.771429,1.028571,0.3125,0.550000,...,1,0,1,0,0,0,1,0,0,0

In [291]:
x_train , x_test , y_train , y_test = train_test_split(X ,Y ,test_size=0.33 , random_state=11 , shuffle=True)

In [292]:
from sklearn.linear_model import LinearRegression
lrm = LinearRegression()
lrm.fit(X,Y)

LinearRegression()

In [294]:
lrm.score(X,Y)

0.9153645524256047

In [304]:
from sklearn.linear_model import Lasso
las = Lasso(normalize=True , max_iter=100000 , alpha = 0.01)

In [305]:
las.fit(X ,Y)

Lasso(alpha=0.01, max_iter=100000, normalize=True)

In [306]:
las.score(X ,Y)

0.9153643438420522